language: R
sudo: false
cache: packages
r:
  - oldrel
  - release
  - devel

use_bioc: true

r_github_packages:
  - aloysius-lim/bigrf
  
bioc_packages:
  - RBGL
  - graph
  - Vennerable
  - BiocInstaller
  
